spring:
  datasource:
    url: jdbc:mysql://192.168.2.161:3306/bookinfo?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: my_password
  #    hikari:
  #      jdbc-url: jdbc:mysql://192.168.1.4:6603/bookinfo?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
  #      username: root
  #      password: mypassword
  #      connection-timeout: 30000
  #      auto-commit: true
  #      idle-timeout: 600000
  #      maximum-pool-size: 50
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.2.161
    port: 5672
    username: admin
    password: mypassword
    virtual-host: /
jsa:
  rabbitmq:
    queue: jsa.queue1
    exchange: jsa.exchange.direct1
    routingkey: jsa.routingkey1
server:
  port: 8888
mybatis:
  type-aliases-package: com.example.rabbitmqdemo.model
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml