###
GET http://127.0.0.1:8888/rabbitmq/send?msg=helloworld

###
GET http://127.0.0.1:8888/rabbitmq/sendTTL?msg=helloworld过期时间

###
GET http://127.0.0.1:8888/rabbitmq/producerV1

###
GET http://127.0.0.1:8888/rabbitmq/producerV2

###消息的TTL，方法一：通过设置队列的TTL，队列中的所有消息都有相同的过期时间。
GET http://127.0.0.1:8888/rabbitmq/producerV3

###针对每条消息设置 TTL 的方法是在 channel.basicPublish 方法中加入 expiration的属性参数，单位为毫秒。
GET http://127.0.0.1:8888/rabbitmq/producerV4

###设置队列的 TTL
GET http://127.0.0.1:8888/rabbitmq/producerV5

###死信队列
GET http://127.0.0.1:8888/rabbitmq/producerV6

###优先级队列
GET http://127.0.0.1:8888/rabbitmq/producerV7

###生产者确认,事务机制
GET http://127.0.0.1:8888/rabbitmq/producerV8

###
GET http://127.0.0.1:8888/rabbitmq/consumerV1

###
GET http://127.0.0.1:8888/rabbitmq/consumerV2

###